### ISSUE TITLE
Intervertir XP et Argent

### ISSUE THREAD

**Issue by Piveo** [skychatorg/skychat-bots#3]
Bonjour,

Il me semble que l'XP des utilisateurs fût changer par l'argent ( La monnaie est le "_SKYPOINT_" si je ne m'abuse ... ).
Ainsi il faudrait ré intervertir les données pour obtenir que tout ceci revienne à la normale. Ou alors procédé à un "RESET" que nous pouvons francisé tel une "Remise à Zéro".

Inutile de me reprendre, je sais que ce n'est pas ici qu'est codé votre "Messagerie du Ciel" mais c'est le seul endroit où il semblerait que je puisse vous contacter.

Cordialement,
Piveo.

**Comment by 7PH** [comment]
Le reset est déjà prévu "à cause" d'une récente erreur de développement causée par un des contributeurs du repository `skychat-server` (suivez mon regard @k8th )
En l'occurence les membres du tchat avaient dit NO RESET mais l'admin a compris NOW RESET

**Comment by 7PH** [comment]
En revanche c'est une issue pour l'upstream ça
