### ISSUE TITLE
Render les mask

### ISSUE THREAD

**Issue by kiwec** [skychatorg/skychat-bots#4]
Bonjour,

Render les mask

Cordialement,
kiwec

**Comment by Piveo** [comment]
Bonjour,

Je "plussoie" ( Néologisme signifiant que j'apporte mon soutient à la personne concerné, ici "_Kiwec_" ) l'auteur. Nous voulons que vous nous rendiez les masques que nous avons payé vraiment très cher avec l'argent que vous nous donné. 

Cordialement,
Piveo.

**Comment by 7PH** [comment]
J'ai explosé, 

Cette demande a été transmise à l'administrateur, voici sa réponse:

`bougnadaire`

Je vous laisse soin d'interprêter sa réponse comme il se doit,

Madame, Monsieur, Je vous prie de croire en l'assurance de mes respectueuses issoutations
