### ISSUE TITLE
Correction du safespace mode pour le bot de modération

### ISSUE THREAD

**Issue by 7PH** [skychatorg/skychat-bots#9]
Je propose de rajouter des termes offensifs dans la liste de mots interdits afin que le skychat reste un safe space

**Comment by 7PH** [comment]
J'attends vos propositions
@ogbaba @RogerDuGhetto @k8th @ssoflashy

**Comment by ogbaba** [comment]
pd, féminazi, tapette, fiotte, shiappa, pédale
Ce sont des termes blessants envers la communauté LGBTPD++
